import 'jquery-global.js'
import 'whatwg-fetch'
import 'feature.js'
import 'bootstrap'
import Promise from 'promise-polyfill'
import riot from 'riot'
import anime from 'animejs'
import p5 from 'p5'
import ScrollMagic from 'scrollmagic'
import slick from 'slick-carousel'